# Generated by Django 2.0.5 on 2018-05-19 22:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiveLecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 19, 22, 44, 24, 636173)),
        ),
        migrations.AddField(
            model_name='lecture',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 19, 22, 44, 24, 636144)),
        ),
        migrations.AddField(
            model_name='messages',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LiveLecture.Lecture'),
        ),
        migrations.AddField(
            model_name='messages',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
