# Generated by Django 2.0.5 on 2018-05-19 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveLecture', '0002_auto_20180519_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 19, 22, 57, 27, 810927)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 19, 22, 57, 27, 810898)),
        ),
    ]
